banned_words = [
    'puto',
    'Donal_trump',
    'gonorrea',
    "barack obama",
    "elon musk",
    "oprah winfrey",
    "beyoncé",
    "cristiano ronaldo",
    "taylor swift",
    "angelina jolie",
    "bill gates",
    "emma watson",
    "jeff bezos",
    "pope francis",
    "lionel messi",
    "kim kardashian",
    "donald trump",
    "malala yousafzai",
    "adele",
    "narendra modi",
    "serena williams",
    "kanye west",
    "queen elizabeth ii",
    "leonardo dicaprio",
    "jennifer lawrence",
    "mark zuckerberg",
    "rihanna",
    "brad pitt",
    "ellen degeneres",
    "george clooney",
    "ariana grande",
    "will smith",
    "meryl streep",
    "miley cyrus",
    "sachin tendulkar",
    "david beckham",
    "kylie jenner",
    "tom hanks",
    "gisele bündchen",
    "j.k. rowling",
    "emma stone",
    "jeffree star",
    "selena gomez",
    "dwayne johnson",
    "julia roberts",
    "pewdiepie",
    "stephen curry",
    "benedict cumberbatch",
    "jennifer aniston",
    "hugh jackman",
    "kim jong-un",
    "snoop dogg",
    "neymar",
    "aishwarya rai bachchan",
    "harrison ford",
    "eminem",
    "demi lovato",
    "gwyneth paltrow",
    "morgan freeman",
    "katy perry",
    "johnny depp",
    "scarlett johansson",
    "billie eilish",
    "cate blanchett",
    "dwayne wade",
    "keanu reeves",
    "gal gadot",
    "zendaya",
    "kevin hart",
    "margot robbie",
    "chris hemsworth",
    "tom brady",
    "shah rukh khan",
    "daniel radcliffe",
    "rafael nadal",
    "angelina jolie",
    "eddie murphy",
    "hugh grant",
    "nicole kidman",
    "steve jobs",
    "ryan reynolds",
    "alicia keys",
    "jim carrey",
    "zlatan ibrahimović",
    "julianne moore",
    "daniel craig",
    "michael jordan",
    "jennifer lopez",
    "kate middleton",
    "naomi osaka",
    "rihanna",
    "stephen king",
    "melissa mccarthy",
    "bruce willis",
    "john legend",
    "roger federer",
    "amy adams",
    "gordon ramsay",
    "priyanka chopra"
]