# Generated by Django 4.1 on 2023-08-18 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='answer',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='img',
            field=models.ImageField(blank=True, upload_to='profile_img/'),
        ),
        migrations.AddField(
            model_name='user',
            name='question',
            field=models.CharField(default='Cual es el primer nombre de tu papa?', max_length=100),
        ),
    ]
