# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import server_pb2 as server__pb2


class ConvertidorUrlsStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ConvertirUrls = channel.unary_unary(
                '/distribuidos.ConvertidorUrls/ConvertirUrls',
                request_serializer=server__pb2.ConvertirUrlsRequest.SerializeToString,
                response_deserializer=server__pb2.ConvertirUrlsResponse.FromString,
                )


class ConvertidorUrlsServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ConvertirUrls(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ConvertidorUrlsServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ConvertirUrls': grpc.unary_unary_rpc_method_handler(
                    servicer.ConvertirUrls,
                    request_deserializer=server__pb2.ConvertirUrlsRequest.FromString,
                    response_serializer=server__pb2.ConvertirUrlsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'distribuidos.ConvertidorUrls', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ConvertidorUrls(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ConvertirUrls(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/distribuidos.ConvertidorUrls/ConvertirUrls',
            server__pb2.ConvertirUrlsRequest.SerializeToString,
            server__pb2.ConvertirUrlsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)


class ConvertidorOfficeStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ConvertirArchivos = channel.unary_unary(
                '/distribuidos.ConvertidorOffice/ConvertirArchivos',
                request_serializer=server__pb2.ConvertirArchivosRequest.SerializeToString,
                response_deserializer=server__pb2.ConvertirArchivosResponse.FromString,
                )


class ConvertidorOfficeServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ConvertirArchivos(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ConvertidorOfficeServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ConvertirArchivos': grpc.unary_unary_rpc_method_handler(
                    servicer.ConvertirArchivos,
                    request_deserializer=server__pb2.ConvertirArchivosRequest.FromString,
                    response_serializer=server__pb2.ConvertirArchivosResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'distribuidos.ConvertidorOffice', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ConvertidorOffice(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ConvertirArchivos(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/distribuidos.ConvertidorOffice/ConvertirArchivos',
            server__pb2.ConvertirArchivosRequest.SerializeToString,
            server__pb2.ConvertirArchivosResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
