"""
Django settings for User_custom_ldap project.

Generated by 'django-admin startproject' using Django 4.1.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

from pathlib import Path
import ldap
from django_auth_ldap.config import LDAPSearch, ActiveDirectoryGroupType
import os
from datetime import timedelta

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-om1*3sf1q58@@fo3ti(1g%$2voc8+vq&xh==v7hd5i6-jvh^3@'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['177.200.63.241','20.25.34.123','*','https://api.thenexusbattles2.cloud/login-api/','api.thenexusbattles2.cloud/login-api/','api.thenexusbattles2.cloud']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'django_auth_ldap',
    'rest_framework_simplejwt',
    'corsheaders',
    'Users',
    'Files'
]

SESSION_COOKIE_DOMAIN = 'thenexusbattles2.cloud'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

CORS_ALLOW_ALL_ORIGINS = True

ROOT_URLCONF = 'User_custom_ldap.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ['templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'User_custom_ldap.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

"""
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'Users',
        'USER': 'root',
        'PASSWORD': 'Nexusbattles2_',
        'HOST': 'db',
        'PORT': '3306',
    }
}
"""
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATIC_URL = 'static/'

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR /'media'

# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

##uso del modelo personalizado del usuario
AUTH_USER_MODEL = 'Users.User'

####configuracion de conexion con el directorio activo
AUTH_LDAP_SERVER_URI = "ldap://192.168.1.72:389"
AUTH_LDAP_BIND_DN = "CN=Administrador,CN=Users,DC=distribuidos,DC=com"
AUTH_LDAP_BIND_PASSWORD = "Jagua456"
AUTH_LDAP_USER_SEARCH = LDAPSearch("dc=distribuidos,dc=com", ldap.SCOPE_SUBTREE, "(sAMAccountName=%(user)s)")
#atributos del usuario del directorio activo y django
AUTH_LDAP_USER_ATTR_MAP = {
    "username": "sAMAccountName",
    "name":"givenName",
    "last_name": "sn",
    "email":"mail"
}
##configuracion de grupos y permisos del directorio
AUTH_LDAP_GROUP_SEARCH = LDAPSearch(
            "dc=distribuidos,dc=com", ldap.SCOPE_SUBTREE, "(objectCategory=Group)"
            )
AUTH_LDAP_GROUP_TYPE = ActiveDirectoryGroupType(name_attr="cn")
#AUTH_LDAP_USER_FLAGS_BY_GROUP = {
#            "is_superuser": "CN=django-admins,CN=Users,DC=distribuidos,DC=com",
#            "is_admin": "CN=django-admins,CN=Users,DC=distribuidos,DC=com",
#            "is_staff": "CN=django-admins,CN=Users,DC=distribuidos,DC=com",
#            "is_active": "CN=django-users,CN=Users,DC=distribuidos,DC=com"
#            }

AUTH_LDAP_FIND_GROUP_PERMS = True
AUTH_LDAP_CACHE_GROUPS = True
##tiempo de acceso
AUTH_LDAP_GROUP_CACHE_TIMEOUT = 1  # 1 hour cache

##definimos la autenticacion de la aplicacion, primero por LDAP
AUTHENTICATION_BACKENDS = [
            'Users.custom_ldap_backend.CustomLDAPBackend',
            'django.contrib.auth.backends.ModelBackend',
]

##Configuracion de los tokens JWT
SIMPLE_JWT = {
    'AUTH_HEADER_TYPES': ('Bearer',),
    'USER_ID_FIELD': 'username',
    'USER_ID_CLAIM': 'user_id',
    'SIGNING_KEY': '3eaf50158d956cef59f00c45a42cabb143a8c6e8e26492ab8bac12dd6a2a2221', 
    "ACCESS_TOKEN_LIFETIME": timedelta(days=1),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=2),
    "TOKEN_OBTAIN_SERIALIZER": "Users.tokens.MyTokenObtainPairSerializer"
}

##configuracion de DRF
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'Users.tokens.CustomJWTAuthentication', ##generacion de tokens para el login con LDAP
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 5, 
}

##configuracion de conexion con la api de gmail
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_HOST_USER = 'nexus.battles.2023@gmail.com' #nexusbattles2023
EMAIL_HOST_PASSWORD = 'psywhggkdnfvzorp'
EMAIL_USE_TLS = True
